'use client';
import { useState } from 'react';
import { AlertTriangle, Calculator, ChevronDown, Clock, FileSearch, FileText, Globe, Image as ImageIcon, Loader2, Search, Server, Sparkles, Trash2 } from 'lucide-react';
import { FileEditCard } from '@/components/agent/file-edit-card';
import type { FileDiff } from '@/lib/diff/compute-diff';
import { cn } from '@/lib/utils';
export interface ToolPartViewData { toolName: string; state: string; input: unknown; output?: unknown; errorText?: string; }
const TOOL_ICONS: Record<string, typeof Search> = { web_search: Search, page_reader: Globe, image_gen: ImageIcon, clock: Clock, calculator: Calculator, studio_uuid: Server, studio_dice: Server, studio_lorem: Server, studio_base64: Server, read_file: FileText, search_files: FileSearch, delete_file: Trash2 };
const TOOL_LABELS: Record<string,string> = { web_search:'Búsqueda web', page_reader:'Lector web', image_gen:'Generador de imágenes', clock:'Reloj', calculator:'Calculadora', read_file:'Leer archivo', search_files:'Buscar archivos', delete_file:'Eliminar archivo' };
const FILE_EDIT_TOOLS = new Set(['write_file','edit_file','delete_file']);
function outputToText(output: unknown): string { if (output == null) return ''; if (typeof output === 'string') return output; if (typeof output === 'object') { const r=output as Record<string,unknown>; if(typeof r.content==='string') return r.content; if(typeof r.error==='string') return `Error: ${r.error}`; return JSON.stringify(output,null,2); } return String(output); }
function isFileEditOutput(output: unknown): output is { pendingEditId:string; diff:FileDiff } { return typeof output==='object' && output!==null && typeof (output as Record<string,unknown>).pendingEditId==='string' && typeof (output as Record<string,unknown>).diff==='object'; }
export function ToolPart({ part }: { part: ToolPartViewData }) { const [open,setOpen]=useState(false); if(FILE_EDIT_TOOLS.has(part.toolName)&&part.state==='output-available'&&isFileEditOutput(part.output)) return <FileEditCard pendingEditId={part.output.pendingEditId} diff={part.output.diff}/>; const Icon=TOOL_ICONS[part.toolName]??Sparkles; const label=TOOL_LABELS[part.toolName]??part.toolName; const running=part.state==='input-streaming'||part.state==='input-available'; const failed=part.state==='output-error'||part.state==='output-denied'; const outputText=part.state==='output-available'?outputToText(part.output):part.errorText??''; const isImage=part.toolName==='image_gen'&&outputText.startsWith('/'); return <div className="my-1.5 overflow-hidden rounded-xl border border-border/50 bg-card/50 text-xs"><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="flex w-full items-center gap-2 px-3 py-2 text-left hover:bg-accent/40">{running?<Loader2 className="size-3.5 animate-spin text-muted-foreground"/>:failed?<AlertTriangle className="size-3.5 text-destructive"/>:<Icon className="size-3.5 text-muted-foreground"/>}<span className="min-w-0 flex-1 truncate"><span className="font-medium">{label}</span><span className="ml-1.5 text-muted-foreground">{running?'ejecutando…':failed?'falló':isImage?'imagen lista':'completado'}</span></span><ChevronDown className={cn('size-3.5 text-muted-foreground',open&&'rotate-180')}/></button>{open&&<div className="border-t border-border/40 px-3 py-2"><p className="mb-1 text-[10px] uppercase tracking-wide text-muted-foreground/60">Argumentos</p><pre className="max-h-32 overflow-auto whitespace-pre-wrap break-all rounded-md bg-muted/40 p-2 font-mono text-[10.5px]">{JSON.stringify(part.input,null,2)}</pre>{part.state==='output-available'&&<><p className="mb-1 mt-2 text-[10px] uppercase tracking-wide text-muted-foreground/60">Resultado</p>{isImage?<img src={outputText} alt="Imagen generada" className="max-h-72 rounded-lg border border-border/40"/>:<pre className="max-h-48 overflow-auto whitespace-pre-wrap break-words rounded-md bg-muted/40 p-2 font-mono text-[10.5px]">{outputText.slice(0,4000)||'(vacío)'}</pre>}</>}{failed&&<p className="mt-2 text-destructive">{part.errorText??'Error desconocido.'}</p>}</div>}</div>; }
